# docker-compose.yml
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tu_app_php
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      # Persistencia de storage para logs, cache y uploads
      - app_storage:/var/www/html/storage
      # Monta todo el código para poder hacer build de assets y ejecutar artisan
      - ./:/var/www/html
      # Asegura que Laravel lea el .env real
      - ./.env:/var/www/html/.env:ro
    # Inyecta las variables de .env en el entorno de Docker
    env_file:
      - .env
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    container_name: tu_app_nginx
    restart: unless-stopped
    volumes:
      # Configuración de Nginx
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      # Servir solamente la carpeta public (incluye build/assets)
      - ./public:/var/www/html/public:ro
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  app_storage:
    driver: local
